- hosts: localhost
  connection: local
  tasks:
  - name: install oh-my-zsh 
    become: true
    become_user: maba
    shell: sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"
  - copy: src=~/projects/dotfiles/.tmux.conf dest=~/.tmux.conf owner=maba mode=755
  - copy: src=~/projects/dotfiles/.gitconfig dest=~/.gitconfig owner=maba mode=755
  - copy: src=~/projects/dotfiles/.zshrc dest=~/.zshrc owner=maba mode=755
  - copy: src=~/projects/dotfiles/.zsh dest=~/ owner=maba mode=755
  - copy: src=~/projects/dotfiles/.vimrc dest=~/.vimrc owner=maba mode=755
  - copy: src=~/projects/dotfiles/.vim dest=~/ owner=maba mode=755
  - name: cloning vundle
    become: true
    become_user: maba
    git: repo=git@github.com:VundleVim/{{ item.repo }}.git
         dest={{ item.dest }}
    with_items:
      - dest: "~/.vim/bundle/Vundle.vim"
        repo: Vundle.vim
  - name: install vim plugins 
    become_user: true
    shell: "vim +PluginInstall +qall"    
  - name: set zsh default shell
    user: name=maba shell=/usr/bin/zsh
    become: true
  - pip: name=virtualenvwrapper
    become: true
